spring:
  application:
    name: web-backend
  datasource:
    url: jdbc:mysql://localhost:3306/database1
    username: root
    password: long@1402
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true